[project]
name = "evaluador-algoritmia"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Juan Osorio", email = "96839034+JuanOsorioa@users.noreply.github.com"},
]
dependencies = [
    "streamlit>=1.62.0",
    "sqlalchemy>=2.0.52",
    "psycopg[binary]>=3.3.4",
]
requires-python = "==3.14.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false


[tool.poetry]
package-mode = false